<?php
$web_online=$tablepre.'online';
$web_column=$tablepre.'column';
$web_news=$tablepre.'news';
$web_product=$tablepre.'product';
$web_download=$tablepre.'download';
$web_img=$tablepre.'img';
$web_index=$tablepre.'index';
$web_link=$tablepre.'link';
$web_parameter=$tablepre.'parameter';
$web_img=$tablepre.'img';
$web_job=$tablepre.'job';
$web_fdlist=$tablepre.'fdlist';
$web_fdparameter=$tablepre.'fdparameter';
$web_feedback=$tablepre.'feedback';
$web_message=$tablepre.'message';
$web_admin_table=$tablepre.'admin_table';
$web_skin_table=$tablepre.'skin_table';
$web_online=$tablepre.'online';
?>